---

####### Firewalld setup ##########
- name: Import firewall rules tasks
  import_tasks: firewalld.yml
  tags:
    - firewalld

##### Pre satellite installation tasks #########
- name: Stat {{ env_type }}/satellite_pre_installation.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_pre_installation.yml
  register: __pre_installation

- name: Include Satellite Pre_tasks
  include_tasks: ./configs/{{ env_type }}/satellite_pre_installation.yml
  when: __pre_installation.stat.exists 

####### Include satellite tasks #############
- name: Include satellite installation/setup tasks
  include_tasks: version_6.x.yml
  when: satellite_version is defined
  tags:
    - installation
    - configuration

##### Post satellite configuration tasks #########
- name: Stat {{ env_type }}/satellite_post_configuration.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_post_configuration.yml
  register: __post_configuration

- name: Include Satellite Post_tasks
  include_tasks: ./configs/{{ env_type }}/satellite_post_configuration.yml
  when: __post_configuration.stat.exists 
