---

####### Firewalld setup ##########
- name: Import firewall rules tasks
  import_tasks: firewalld.yml
  tags:
    - install_firewall

##### Pre satellite installation tasks #########
- name: Collecting stat of ./configs/{{ env_type }}/satellite_pre_installation.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_pre_installation.yml
  register: __pre_installation
  tags:
    - install_satellite

- name: Satellite Pre-installation tasks
  include_tasks: ./configs/{{ env_type }}/satellite_pre_installation.yml
  when: __pre_installation.stat.exists 
  tags:
    - install_satellite

####### Include satellite tasks #############
- name: Include satellite installation/setup tasks
  include_tasks: version_6.x.yml
  when: satellite_version is defined

##### Post satellite configuration tasks #########
- name: Collecting stat of ./configs/{{ env_type }}/satellite_post_configuration.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_post_configuration.yml
  register: __post_configuration
  tags:
    - configure_satellite

- name: Satellite Post-configuration tasks
  include_tasks: ./configs/{{ env_type }}/satellite_post_configuration.yml
  tags:
    - configure_satellite
    
  when: __post_configuration.stat.exists 
