---

- name: Update satellite node
  package:
    name: '*'
    state: present
  tags:
    - install_satellite

- name: Install Satellite Package
  package:
    name: satellite-{{ satellite_version }}*.el7*
    state: present
  async: 3600
  poll: 60
  tags:
    - install_satellite

####### Satellite Post Installation Tasks ###############
- name: Collecting stat of ./configs/{{ env_type }}/satellite_post_installation.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_post_installation.yml
  register: __post_installation
  tags:
    - install_satellite

- name: Satellite Post-installation tasks
  include_tasks: ./configs/{{ env_type }}/satellite_post_installation.yml
  when: __pre_installation.stat.exists
  tags:
    - install_satellite

####### Satellite Pre Configuration Tasks ###############
- name: Collecting stat of ./configs/{{ env_type }}/satellite_pre_configuration.yml file
  stat:
    path: ./configs/{{ env_type }}/satellite_pre_configuration.yml
  register: __pre_configuration
  tags:
    - configuration_satellite

- name: Satellite Pre-configuration tasks
  include_tasks: ./configs/{{ env_type }}/satellite_pre_configuration.yml
  when: __pre_configuration.stat.exists
  tags:
    - configure_satellite

########### Satellite Configuration ########
- name: configure satellite
  command: >-
    satellite-installer
    {% if '--scenario' not in satellite_arguments %} --scenario satellite{% endif %}
    {% if '-admin-username' not in satellite_arguments %}
    {% if satellite_version is version('6.4', '<=') %} --foreman-admin-username {{ satellite_admin | default('admin') }}
    {% else %} --foreman-initial-admin-username {{ satellite_admin | default('admin') }}{% endif %}
    {% endif %}
    {% if '-admin-password' not in satellite_arguments %}
    {% if satellite_version is version('6.4', '<=') %} --foreman-admin-password {{ satellite_admin_password }}
    {% else %} --foreman-initial-admin-password {{ satellite_admin_password }}{% endif %}
    {% endif %}
    {% if 'certs-cname' not in satellite_arguments %} --certs-cname {{ inventory_hostname }}{% endif %}
    {% if satellite_arguments is defined %}
    {% for satellite_arguments in satellite_arguments %}
    {{ satellite_arguments }}
    {% endfor %}
    {% endif %}
  register: command_output
  changed_when: 'command_output.rc == 0'
  async: 3600
  poll: 60
  tags:
    - install_satellite
